#!/bin/bash

mkdir temp_for_dotfiles
cd temp_for_dotfiles
git clone https://github.com/trulybruly/linux-welcome-installers

cd linux-welcome-installers
echo "what kind of setup is it?"
echo "1 - full arch"
echo "2 - server/raspberry debian"
read _type

if [ $_type -eq 1 ]; then
    sh full-arch-gnome/full_arch.sh
elif [ $_type -eq 2 ]; then
    sh debian/server_deb.sh
fi

cd ../..
rm -rf temp_for_dotfiles